### ISSUE TITLE
Why use `get-clean-string` ?

### ISSUE THREAD

**Issue by maranomynet** [webdacjs/simple-map-cache#5]
Hi. I'm curious, what is the reasoning behind passing every cache-key through `get-clean-string` before use?

Shouldn't any old string be a syntatically valid key for the Map?

**Comment by webdacjs** [comment]
Yeah that's a fair point. Actually in the newest version I changed this implementation, dropping the `get-clean-string` call and supporting persistence. Thanks for your question.
